# Generated by Django 3.0.7 on 2020-06-30 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11)),
                ('birthdate', models.DateField()),
                ('amount_asked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('terms_asked', models.IntegerField(choices=[(6, 'Six'), (9, 'Nine'), (12, 'Twelve')])),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='processing', max_length=10)),
                ('result', models.CharField(max_length=8, null=True)),
                ('refused_policy', models.CharField(max_length=10, null=True)),
                ('amount_approved', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('terms_approved', models.IntegerField(null=True)),
            ],
        ),
    ]
