# Generated by Django 3.0.7 on 2020-07-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_approved',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_asked',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
